FROM python:3.11

WORKDIR /app

COPY src/frontend/requirements.txt /app/src/frontend/requirements.txt
RUN pip install --no-cache-dir -r /app/src/frontend/requirements.txt

COPY src /app/src
COPY src/frontend/public /app/public
COPY src/frontend/.chainlit /app/.chainlit

CMD ["chainlit", "run", "/app/src/frontend/app.py", "--host", "0.0.0.0", "--port", "80"]