FROM python:3.11

WORKDIR /app

COPY ./src/container-app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/container-app ./container_app

CMD ["uvicorn", "container_app.main:app", "--host", "0.0.0.0", "--port", "80"]