param sites_liotrag_afa_name string = 'liotrag-afa'
param Redis_liotrag_acr_name string = 'liotrag-acr'
param containerapps_liotrag_aca_name string = 'liotrag-aca'
param vaults_liotrag_vault_name string = 'liotrag-vault'
param searchServices_litrag_ais_name string = 'litrag-ais'
param serverfarms_ASP_LiotRAG_80b6_name string = 'ASP-LiotRAG-80b6'
param storageAccounts_liotragblob_name string = 'liotragblob'
param containerapps_liotrag_frontend_aca_name string = 'liotrag-frontend-aca'
param registries_liotragreg_name string = 'liotragreg'
param accounts_liotrag_openai_2_name string = 'liotrag-openai-2'
param managedEnvironments_managedEnvironment_LiotRAG_873c_name string = 'managedEnvironment-LiotRAG-873c'

resource managedEnvironments_managedEnvironment_LiotRAG_873c_name_resource 'Microsoft.App/managedEnvironments@2025-02-02-preview' = {
  name: managedEnvironments_managedEnvironment_LiotRAG_873c_name
  location: 'West US 2'
  tags: {
    Project: 'LiotRAG'
    Course: 'Sistemi-Cloud'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    appLogsConfiguration: {
      destination: 'azure-monitor'
    }
    zoneRedundant: false
    kedaConfiguration: {}
    daprConfiguration: {}
    customDomainConfiguration: {}
    workloadProfiles: [
      {
        workloadProfileType: 'Consumption'
        name: 'Consumption'
        enableFips: false
      }
    ]
    peerAuthentication: {
      mtls: {
        enabled: false
      }
    }
    peerTrafficConfiguration: {
      encryption: {
        enabled: false
      }
    }
    publicNetworkAccess: 'Enabled'
  }
}

resource Redis_liotrag_acr_name_resource 'Microsoft.Cache/Redis@2024-11-01' = {
  name: Redis_liotrag_acr_name
  location: 'East US 2'
  tags: {
    Project: 'LiotRAG'
    Course: 'Sistemi-Cloud'
  }
  properties: {
    redisVersion: '6.0'
    sku: {
      name: 'Basic'
      family: 'C'
      capacity: 0
    }
    enableNonSslPort: false
    minimumTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
    redisConfiguration: {
      'aad-enabled': 'true'
      maxclients: '256'
      'maxmemory-reserved': '30'
      'maxfragmentationmemory-reserved': '30'
      'maxmemory-delta': '30'
    }
    updateChannel: 'Stable'
    disableAccessKeyAuthentication: false
  }
}

resource accounts_liotrag_openai_2_name_resource 'Microsoft.CognitiveServices/accounts@2025-06-01' = {
  name: accounts_liotrag_openai_2_name
  location: 'swedencentral'
  tags: {
    Course: 'Sistemi-Cloud'
    Project: 'LiotRAG'
  }
  sku: {
    name: 'S0'
  }
  kind: 'OpenAI'
  properties: {
    apiProperties: {}
    customSubDomainName: accounts_liotrag_openai_2_name
    networkAcls: {
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    allowProjectManagement: false
    publicNetworkAccess: 'Enabled'
  }
}

resource registries_liotragreg_name_resource 'Microsoft.ContainerRegistry/registries@2025-05-01-preview' = {
  name: registries_liotragreg_name
  location: 'eastus2'
  tags: {
    Project: 'LiotRAG'
    Course: 'Sistemi-Cloud'
  }
  sku: {
    name: 'Basic'
    tier: 'Basic'
  }
  properties: {
    adminUserEnabled: false
    policies: {
      quarantinePolicy: {
        status: 'disabled'
      }
      trustPolicy: {
        type: 'Notary'
        status: 'disabled'
      }
      retentionPolicy: {
        days: 7
        status: 'disabled'
      }
      exportPolicy: {
        status: 'enabled'
      }
      azureADAuthenticationAsArmPolicy: {
        status: 'enabled'
      }
      softDeletePolicy: {
        retentionDays: 7
        status: 'disabled'
      }
    }
    encryption: {
      status: 'disabled'
    }
    dataEndpointEnabled: false
    publicNetworkAccess: 'Enabled'
    networkRuleBypassOptions: 'AzureServices'
    networkRuleBypassAllowedForTasks: false
    zoneRedundancy: 'Disabled'
    anonymousPullEnabled: false
    metadataSearch: 'Disabled'
    roleAssignmentMode: 'LegacyRegistryPermissions'
    autoGeneratedDomainNameLabelScope: 'NoReuse'
  }
}

resource vaults_liotrag_vault_name_resource 'Microsoft.KeyVault/vaults@2024-12-01-preview' = {
  name: vaults_liotrag_vault_name
  location: 'eastus2'
  tags: {
    Course: 'Sistemi-Cloud'
    Project: 'LiotRAG'
  }
  properties: {
    sku: {
      family: 'A'
      name: 'Standard'
    }
    tenantId: '2478a01d-6b2e-446e-b265-934b190bb10f'
    networkAcls: {
      bypass: 'None'
      defaultAction: 'Allow'
      ipRules: []
      virtualNetworkRules: []
    }
    accessPolicies: []
    enabledForDeployment: false
    enabledForDiskEncryption: false
    enabledForTemplateDeployment: false
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enableRbacAuthorization: true
    vaultUri: 'https://${vaults_liotrag_vault_name}.vault.azure.net/'
    provisioningState: 'Succeeded'
    publicNetworkAccess: 'Enabled'
  }
}

resource searchServices_litrag_ais_name_resource 'Microsoft.Search/searchServices@2025-05-01' = {
  name: searchServices_litrag_ais_name
  location: 'Central US'
  tags: {
    Project: 'LiotRAG'
    Course: 'Sistemi-Cloud'
  }
  sku: {
    name: 'basic'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    replicaCount: 1
    partitionCount: 1
    endpoint: 'https://${searchServices_litrag_ais_name}.search.windows.net'
    hostingMode: 'default'
    computeType: 'Default'
    publicNetworkAccess: 'Enabled'
    networkRuleSet: {
      ipRules: []
      bypass: 'None'
    }
    encryptionWithCmk: {
      enforcement: 'Unspecified'
    }
    disableLocalAuth: false
    authOptions: {
      apiKeyOnly: {}
    }
    dataExfiltrationProtections: []
    semanticSearch: 'free'
    upgradeAvailable: 'notAvailable'
  }
}

resource storageAccounts_liotragblob_name_resource 'Microsoft.Storage/storageAccounts@2025-01-01' = {
  name: storageAccounts_liotragblob_name
  location: 'eastus'
  tags: {
    Project: 'LiotRAG'
    Course: 'Sistemi-Cloud'
  }
  sku: {
    name: 'Standard_RAGRS'
    tier: 'Standard'
  }
  kind: 'StorageV2'
  properties: {
    dnsEndpointType: 'Standard'
    defaultToOAuthAuthentication: false
    publicNetworkAccess: 'Enabled'
    allowCrossTenantReplication: false
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: true
    largeFileSharesState: 'Enabled'
    networkAcls: {
      bypass: 'AzureServices'
      virtualNetworkRules: []
      ipRules: []
      defaultAction: 'Allow'
    }
    supportsHttpsTrafficOnly: true
    encryption: {
      requireInfrastructureEncryption: false
      services: {
        file: {
          keyType: 'Account'
          enabled: true
        }
        blob: {
          keyType: 'Account'
          enabled: true
        }
      }
      keySource: 'Microsoft.Storage'
    }
    accessTier: 'Hot'
  }
}

resource serverfarms_ASP_LiotRAG_80b6_name_resource 'Microsoft.Web/serverfarms@2024-11-01' = {
  name: serverfarms_ASP_LiotRAG_80b6_name
  location: 'Canada Central'
  tags: {
    Course: 'Sistemi-Cloud'
    Project: 'LiotRAG'
  }
  sku: {
    name: 'Y1'
    tier: 'Dynamic'
    size: 'Y1'
    family: 'Y'
    capacity: 0
  }
  kind: 'functionapp'
  properties: {
    perSiteScaling: false
    elasticScaleEnabled: false
    maximumElasticWorkerCount: 1
    isSpot: false
    reserved: true
    isXenon: false
    hyperV: false
    targetWorkerCount: 0
    targetWorkerSizeId: 0
    zoneRedundant: false
    asyncScalingEnabled: false
  }
}

resource containerapps_liotrag_aca_name_resource 'Microsoft.App/containerapps@2025-02-02-preview' = {
  name: containerapps_liotrag_aca_name
  location: 'West US 2'
  tags: {
    Project: 'LiotRAG'
    Course: 'Sistemi-Cloud'
  }
  kind: 'containerapps'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    managedEnvironmentId: managedEnvironments_managedEnvironment_LiotRAG_873c_name_resource.id
    environmentId: managedEnvironments_managedEnvironment_LiotRAG_873c_name_resource.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 80
        exposedPort: 0
        transport: 'Auto'
        traffic: [
          {
            weight: 100
            latestRevision: true
          }
        ]
        allowInsecure: false
        stickySessions: {
          affinity: 'none'
        }
      }
      registries: [
        {
          server: 'liotragreg-c4bkd9gsh4b8dege.azurecr.io'
          identity: 'system-environment'
        }
      ]
      identitySettings: []
      maxInactiveRevisions: 100
    }
    template: {
      containers: [
        {
          image: 'liotragreg-c4bkd9gsh4b8dege.azurecr.io/${containerapps_liotrag_aca_name}:main-e4342b3'
          imageType: 'ContainerImage'
          name: containerapps_liotrag_aca_name
          env: [
            {
              name: 'KEY_VAULT_URL'
              value: 'https://liotrag-vault.vault.azure.net/'
            }
            {
              name: 'AZURE_REDIS_CACHE_SECRET_NAME'
              value: 'Azure-Redis-Cache-Conn-String'
            }
            {
              name: 'AZURE_OPENAI_SECRET_NAME'
              value: 'Azure-OpenAI-Service-IKEAy'
            }
            {
              name: 'AZURE_AI_SEARCH_SECRET_NAME'
              value: 'Azure-AI-Search-Query-Key'
            }
            {
              name: 'AZURE_AI_SEARCH_URL'
              value: 'https://litrag-ais.search.windows.net'
            }
            {
              name: 'AZURE_AI_SEARCH_INDEX_NAME'
              value: 'rag-unict'
            }
            {
              name: 'AZURE_OPENAI_ENDPOINT'
              value: 'https://liotrag-openai-2.openai.azure.com/'
            }
            {
              name: 'AZURE_OPENAI_DEPLOYMENT'
              value: 'gpt-4.1-mini'
            }
            {
              name: 'AZURE_OPENAI_API_VERSION'
              value: '2024-12-01-preview'
            }
            {
              name: 'REDIS_TTL_SECONDS'
              value: '3600'
            }
            {
              name: 'MAX_HISTORY_TURNS'
              value: '4'
            }
            {
              name: 'AZURE_ENTRAID_CLIENT_ID'
              value: '2e2a0d4a-4a46-4fd6-971f-a31ef7fb91ba'
            }
            {
              name: 'AZURE_TENANT_ID'
              value: '2478a01d-6b2e-446e-b265-934b190bb10f'
            }
            {
              name: 'AZURE_CLIENT_SECRET_NAME'
              value: 'liotrag-app-client-secret'
            }
          ]
          resources: {
            cpu: 1
            memory: '2Gi'
          }
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 10
        cooldownPeriod: 300
        pollingInterval: 30
      }
    }
  }
}

resource containerapps_liotrag_frontend_aca_name_resource 'Microsoft.App/containerapps@2025-02-02-preview' = {
  name: containerapps_liotrag_frontend_aca_name
  location: 'West US 2'
  tags: {
    Project: 'LiotRAG'
    Course: 'Sistemi-Cloud'
  }
  kind: 'containerapps'
  identity: {
    type: 'None'
  }
  properties: {
    managedEnvironmentId: managedEnvironments_managedEnvironment_LiotRAG_873c_name_resource.id
    environmentId: managedEnvironments_managedEnvironment_LiotRAG_873c_name_resource.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 80
        exposedPort: 0
        transport: 'Auto'
        traffic: [
          {
            weight: 100
            latestRevision: true
          }
        ]
        allowInsecure: false
        stickySessions: {
          affinity: 'none'
        }
      }
      registries: [
        {
          server: 'liotragreg-c4bkd9gsh4b8dege.azurecr.io'
          identity: 'system-environment'
        }
      ]
      identitySettings: []
      maxInactiveRevisions: 100
    }
    template: {
      containers: [
        {
          image: 'liotragreg-c4bkd9gsh4b8dege.azurecr.io/${containerapps_liotrag_frontend_aca_name}:main-e4342b3'
          imageType: 'ContainerImage'
          name: containerapps_liotrag_frontend_aca_name
          env: [
            {
              name: 'KEY_VAULT_URL'
              value: 'https://liotrag-vault.vault.azure.net/'
            }
            {
              name: 'AZURE_REDIS_CACHE_SECRET_NAME'
              value: 'Azure-Redis-Cache-Conn-String'
            }
            {
              name: 'AZURE_OPENAI_SECRET_NAME'
              value: 'Azure-OpenAI-Service-IKEAy'
            }
            {
              name: 'AZURE_AI_SEARCH_SECRET_NAME'
              value: 'Azure-AI-Search-Query-Key'
            }
            {
              name: 'AZURE_AI_SEARCH_URL'
              value: 'https://litrag-ais.search.windows.net'
            }
            {
              name: 'AZURE_AI_SEARCH_INDEX_NAME'
              value: 'rag-unict'
            }
            {
              name: 'AZURE_OPENAI_ENDPOINT'
              value: 'https://liotrag-openai-2.openai.azure.com/'
            }
            {
              name: 'AZURE_OPENAI_DEPLOYMENT'
              value: 'gpt-4.1-mini'
            }
            {
              name: 'AZURE_OPENAI_API_VERSION'
              value: '2024-12-01-preview'
            }
            {
              name: 'REDIS_TTL_SECONDS'
              value: '3600'
            }
            {
              name: 'MAX_HISTORY_TURNS'
              value: '4'
            }
            {
              name: 'AZURE_ENTRAID_CLIENT_ID'
              value: '2e2a0d4a-4a46-4fd6-971f-a31ef7fb91ba'
            }
            {
              name: 'AZURE_TENANT_ID'
              value: '2478a01d-6b2e-446e-b265-934b190bb10f'
            }
            {
              name: 'AZURE_CLIENT_SECRET_NAME'
              value: 'liotrag-app-client-secret'
            }
          ]
          resources: {
            cpu: 2
            memory: '4Gi'
          }
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 10
        cooldownPeriod: 300
        pollingInterval: 30
      }
    }
  }
}

resource Redis_liotrag_acr_name_Data_Contributor 'Microsoft.Cache/Redis/accessPolicies@2024-11-01' = {
  parent: Redis_liotrag_acr_name_resource
  name: 'Data Contributor'
  properties: {
    permissions: '+@all -@dangerous +cluster|info +cluster|nodes +cluster|slots allkeys'
  }
}

resource Redis_liotrag_acr_name_Data_Owner 'Microsoft.Cache/Redis/accessPolicies@2024-11-01' = {
  parent: Redis_liotrag_acr_name_resource
  name: 'Data Owner'
  properties: {
    permissions: '+@all allkeys'
  }
}

resource Redis_liotrag_acr_name_Data_Reader 'Microsoft.Cache/Redis/accessPolicies@2024-11-01' = {
  parent: Redis_liotrag_acr_name_resource
  name: 'Data Reader'
  properties: {
    permissions: '+@read +@connection +cluster|info +cluster|nodes +cluster|slots allkeys'
  }
}

resource accounts_liotrag_openai_2_name_Default 'Microsoft.CognitiveServices/accounts/defenderForAISettings@2025-06-01' = {
  parent: accounts_liotrag_openai_2_name_resource
  name: 'Default'
  properties: {
    state: 'Disabled'
  }
}

resource accounts_liotrag_openai_2_name_gpt_4_1_mini 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = {
  parent: accounts_liotrag_openai_2_name_resource
  name: 'gpt-4.1-mini'
  sku: {
    name: 'GlobalStandard'
    capacity: 100
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: 'gpt-4.1-mini'
      version: '2025-04-14'
    }
    versionUpgradeOption: 'NoAutoUpgrade'
    currentCapacity: 100
    raiPolicyName: 'Microsoft.DefaultV2'
  }
}

resource accounts_liotrag_openai_2_name_text_embedding_3_small 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = {
  parent: accounts_liotrag_openai_2_name_resource
  name: 'text-embedding-3-small'
  sku: {
    name: 'GlobalStandard'
    capacity: 150
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: 'text-embedding-3-small'
      version: '1'
    }
    versionUpgradeOption: 'NoAutoUpgrade'
    currentCapacity: 150
    raiPolicyName: 'Microsoft.DefaultV2'
  }
}

resource accounts_liotrag_openai_2_name_Microsoft_Default 'Microsoft.CognitiveServices/accounts/raiPolicies@2025-06-01' = {
  parent: accounts_liotrag_openai_2_name_resource
  name: 'Microsoft.Default'
  properties: {
    mode: 'Blocking'
    contentFilters: [
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
    ]
  }
}

resource accounts_liotrag_openai_2_name_Microsoft_DefaultV2 'Microsoft.CognitiveServices/accounts/raiPolicies@2025-06-01' = {
  parent: accounts_liotrag_openai_2_name_resource
  name: 'Microsoft.DefaultV2'
  properties: {
    mode: 'Blocking'
    contentFilters: [
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Jailbreak'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Protected Material Text'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Protected Material Code'
        blocking: false
        enabled: true
        source: 'Completion'
      }
    ]
  }
}

resource registries_liotragreg_name_repositories_admin 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_liotragreg_name_resource
  name: '_repositories_admin'
  properties: {
    description: 'Can perform all read, write and delete operations on the registry'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
      'repositories/*/content/delete'
    ]
  }
}

resource registries_liotragreg_name_repositories_pull 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_liotragreg_name_resource
  name: '_repositories_pull'
  properties: {
    description: 'Can pull any repository of the registry'
    actions: [
      'repositories/*/content/read'
    ]
  }
}

resource registries_liotragreg_name_repositories_pull_metadata_read 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_liotragreg_name_resource
  name: '_repositories_pull_metadata_read'
  properties: {
    description: 'Can perform all read operations on the registry'
    actions: [
      'repositories/*/content/read'
      'repositories/*/metadata/read'
    ]
  }
}

resource registries_liotragreg_name_repositories_push 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_liotragreg_name_resource
  name: '_repositories_push'
  properties: {
    description: 'Can push to any repository of the registry'
    actions: [
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

resource registries_liotragreg_name_repositories_push_metadata_write 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_liotragreg_name_resource
  name: '_repositories_push_metadata_write'
  properties: {
    description: 'Can perform all read and write operations on the registry'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

resource vaults_liotrag_vault_name_Azure_AI_Search_Query_Key 'Microsoft.KeyVault/vaults/secrets@2024-12-01-preview' = {
  parent: vaults_liotrag_vault_name_resource
  name: 'Azure-AI-Search-Query-Key'
  location: 'eastus2'
  properties: {
    attributes: {
      enabled: true
    }
  }
}

resource vaults_liotrag_vault_name_Azure_OpenAI_Service_IKEAy 'Microsoft.KeyVault/vaults/secrets@2024-12-01-preview' = {
  parent: vaults_liotrag_vault_name_resource
  name: 'Azure-OpenAI-Service-IKEAy'
  location: 'eastus2'
  properties: {
    attributes: {
      enabled: true
    }
  }
}

resource vaults_liotrag_vault_name_Azure_Redis_Cache_Conn_String 'Microsoft.KeyVault/vaults/secrets@2024-12-01-preview' = {
  parent: vaults_liotrag_vault_name_resource
  name: 'Azure-Redis-Cache-Conn-String'
  location: 'eastus2'
  properties: {
    attributes: {
      enabled: true
    }
  }
}

resource vaults_liotrag_vault_name_liotrag_app_client_secret 'Microsoft.KeyVault/vaults/secrets@2024-12-01-preview' = {
  parent: vaults_liotrag_vault_name_resource
  name: 'liotrag-app-client-secret'
  location: 'eastus2'
  properties: {
    attributes: {
      enabled: true
    }
  }
}

resource storageAccounts_liotragblob_name_default 'Microsoft.Storage/storageAccounts/blobServices@2025-01-01' = {
  parent: storageAccounts_liotragblob_name_resource
  name: 'default'
  sku: {
    name: 'Standard_RAGRS'
    tier: 'Standard'
  }
  properties: {
    containerDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
    cors: {
      corsRules: []
    }
    deleteRetentionPolicy: {
      allowPermanentDelete: false
      enabled: true
      days: 7
    }
  }
}

resource Microsoft_Storage_storageAccounts_fileServices_storageAccounts_liotragblob_name_default 'Microsoft.Storage/storageAccounts/fileServices@2025-01-01' = {
  parent: storageAccounts_liotragblob_name_resource
  name: 'default'
  sku: {
    name: 'Standard_RAGRS'
    tier: 'Standard'
  }
  properties: {
    protocolSettings: {
      smb: {}
    }
    cors: {
      corsRules: []
    }
    shareDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}

resource Microsoft_Storage_storageAccounts_queueServices_storageAccounts_liotragblob_name_default 'Microsoft.Storage/storageAccounts/queueServices@2025-01-01' = {
  parent: storageAccounts_liotragblob_name_resource
  name: 'default'
  properties: {
    cors: {
      corsRules: []
    }
  }
}

resource Microsoft_Storage_storageAccounts_tableServices_storageAccounts_liotragblob_name_default 'Microsoft.Storage/storageAccounts/tableServices@2025-01-01' = {
  parent: storageAccounts_liotragblob_name_resource
  name: 'default'
  properties: {
    cors: {
      corsRules: []
    }
  }
}

resource sites_liotrag_afa_name_resource 'Microsoft.Web/sites@2024-11-01' = {
  name: sites_liotrag_afa_name
  location: 'Canada Central'
  tags: {
    Course: 'Sistemi-Cloud'
    Project: 'LiotRAG'
  }
  kind: 'functionapp,linux'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    enabled: true
    hostNameSslStates: [
      {
        name: '${sites_liotrag_afa_name}-ggetd2c2cdcdduea.canadacentral-01.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Standard'
      }
      {
        name: '${sites_liotrag_afa_name}-ggetd2c2cdcdduea.scm.canadacentral-01.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Repository'
      }
    ]
    serverFarmId: serverfarms_ASP_LiotRAG_80b6_name_resource.id
    reserved: true
    isXenon: false
    hyperV: false
    dnsConfiguration: {}
    outboundVnetRouting: {
      allTraffic: false
      applicationTraffic: false
      contentShareTraffic: false
      imagePullTraffic: false
      backupRestoreTraffic: false
    }
    siteConfig: {
      numberOfWorkers: 1
      linuxFxVersion: 'Python|3.11'
      acrUseManagedIdentityCreds: false
      alwaysOn: false
      http20Enabled: false
      functionAppScaleLimit: 200
      minimumElasticInstanceCount: 0
    }
    scmSiteAlsoStopped: false
    clientAffinityEnabled: false
    clientAffinityProxyEnabled: false
    clientCertEnabled: false
    clientCertMode: 'Required'
    hostNamesDisabled: false
    ipMode: 'IPv4'
    customDomainVerificationId: 'D22F4A45BF9FBE493983EB8BEF7B20481B960AE3AD52C0E363BAC93CB620C8A7'
    containerSize: 1536
    dailyMemoryTimeQuota: 0
    httpsOnly: true
    endToEndEncryptionEnabled: false
    redundancyMode: 'None'
    publicNetworkAccess: 'Enabled'
    storageAccountRequired: false
    keyVaultReferenceIdentity: 'SystemAssigned'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

resource sites_liotrag_afa_name_ftp 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-11-01' = {
  parent: sites_liotrag_afa_name_resource
  name: 'ftp'
  location: 'Canada Central'
  tags: {
    Course: 'Sistemi-Cloud'
    Project: 'LiotRAG'
  }
  properties: {
    allow: false
  }
}

resource sites_liotrag_afa_name_scm 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-11-01' = {
  parent: sites_liotrag_afa_name_resource
  name: 'scm'
  location: 'Canada Central'
  tags: {
    Course: 'Sistemi-Cloud'
    Project: 'LiotRAG'
  }
  properties: {
    allow: false
  }
}

resource sites_liotrag_afa_name_web 'Microsoft.Web/sites/config@2024-11-01' = {
  parent: sites_liotrag_afa_name_resource
  name: 'web'
  location: 'Canada Central'
  tags: {
    Course: 'Sistemi-Cloud'
    Project: 'LiotRAG'
  }
  properties: {
    numberOfWorkers: 1
    defaultDocuments: [
      'Default.htm'
      'Default.html'
      'Default.asp'
      'index.htm'
      'index.html'
      'iisstart.htm'
      'default.aspx'
      'index.php'
    ]
    netFrameworkVersion: 'v4.0'
    linuxFxVersion: 'Python|3.11'
    requestTracingEnabled: false
    remoteDebuggingEnabled: false
    httpLoggingEnabled: false
    acrUseManagedIdentityCreds: false
    logsDirectorySizeLimit: 35
    detailedErrorLoggingEnabled: false
    publishingUsername: 'REDACTED'
    scmType: 'None'
    use32BitWorkerProcess: false
    webSocketsEnabled: false
    alwaysOn: false
    managedPipelineMode: 'Integrated'
    virtualApplications: [
      {
        virtualPath: '/'
        physicalPath: 'site\\wwwroot'
        preloadEnabled: false
      }
    ]
    loadBalancing: 'LeastRequests'
    experiments: {
      rampUpRules: []
    }
    autoHealEnabled: false
    vnetRouteAllEnabled: false
    vnetPrivatePortsCount: 0
    publicNetworkAccess: 'Enabled'
    cors: {
      allowedOrigins: [
        'https://portal.azure.com'
      ]
      supportCredentials: false
    }
    localMySqlEnabled: false
    managedServiceIdentityId: 39918
    ipSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    scmIpSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    scmIpSecurityRestrictionsUseMain: false
    http20Enabled: false
    minTlsVersion: '1.2'
    scmMinTlsVersion: '1.2'
    ftpsState: 'FtpsOnly'
    preWarmedInstanceCount: 0
    functionAppScaleLimit: 200
    functionsRuntimeScaleMonitoringEnabled: false
    minimumElasticInstanceCount: 0
    azureStorageAccounts: {}
    http20ProxyFlag: 0
  }
}

resource sites_liotrag_afa_name_sites_liotrag_afa_name_ggetd2c2cdcdduea_canadacentral_01_azurewebsites_net 'Microsoft.Web/sites/hostNameBindings@2024-11-01' = {
  parent: sites_liotrag_afa_name_resource
  name: '${sites_liotrag_afa_name}-ggetd2c2cdcdduea.canadacentral-01.azurewebsites.net'
  location: 'Canada Central'
  properties: {
    siteName: 'liotrag-afa'
    hostNameType: 'Verified'
  }
}

resource storageAccounts_liotragblob_name_default_az_function_code 'Microsoft.Storage/storageAccounts/blobServices/containers@2025-01-01' = {
  parent: storageAccounts_liotragblob_name_default
  name: 'az-function-code'
  properties: {
    immutableStorageWithVersioning: {
      enabled: false
    }
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
    publicAccess: 'None'
  }
  dependsOn: [
    storageAccounts_liotragblob_name_resource
  ]
}

resource storageAccounts_liotragblob_name_default_azure_webjobs_hosts 'Microsoft.Storage/storageAccounts/blobServices/containers@2025-01-01' = {
  parent: storageAccounts_liotragblob_name_default
  name: 'azure-webjobs-hosts'
  properties: {
    immutableStorageWithVersioning: {
      enabled: false
    }
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
    publicAccess: 'None'
  }
  dependsOn: [
    storageAccounts_liotragblob_name_resource
  ]
}

resource storageAccounts_liotragblob_name_default_pages 'Microsoft.Storage/storageAccounts/blobServices/containers@2025-01-01' = {
  parent: storageAccounts_liotragblob_name_default
  name: 'pages'
  properties: {
    immutableStorageWithVersioning: {
      enabled: false
    }
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
    publicAccess: 'None'
  }
  dependsOn: [
    storageAccounts_liotragblob_name_resource
  ]
}
